
services:
  db:
    image: my-mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
      MYSQL_ROOT_HOST: "%"        # ← allow root from other containers
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    container_name: my-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: employees
      DB_USER: root
      DB_PASS: example
    ports:
      - "8080:8080"
