
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    volumes:
      - type: bind
        source: C:/Users/William/Desktop/seMethods/db/sakila
        target: /docker-entrypoint-initdb.d
        read_only: true
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","127.0.0.1","-pexample"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    build: .
    container_name: my-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: employees
      DB_USER: root
      DB_PASS: example
    ports:
      - "8080:8080"
