name: A workflow for my Hello World App

on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: seMethods

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Compile with Maven
        run: mvn -B -DskipTests compile

      - name: Build Docker image
        run: docker build -t semimage -f Dockerfile .

      - name: Run container
        run: docker run -d --rm -p 8080:8080 --name semcontainer semimage

      - name: Show logs
        run: docker logs semcontainer
