name: Build & Compose

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven (skip tests)
        run: mvn -B -DskipTests clean package

      - name: Show target directory
        run: ls -la target/

      # Prefer a step timeout instead of shell `timeout`
      - name: Docker Compose up
        timeout-minutes: 10
        run: docker compose up --build --abort-on-container-exit

      - name: Show container logs
        if: always()
        run: docker compose logs

      - name: Cleanup
        if: always()
        run: docker compose down -v
